
export const mockAuditLogs = [
  {
    id: "log_123456789",
    timestamp: "2025-04-10T09:15:23",
    user: "Dr. John Smith",
    userRole: "Doctor",
    action: "Created new patient record",
    resource: "Patient",
    resourceId: "P-1005",
    details: "Created new patient record for Jane Doe with ID P-1005.\nPatient details include:\n- Name: Jane Doe\n- DOB: 1985-06-15\n- Gender: Female\n- Contact: +1-555-123-4567",
    status: "success",
    category: "user",
    ipAddress: "192.168.1.45"
  },
  {
    id: "log_123456790",
    timestamp: "2025-04-10T10:22:15",
    user: "Nurse Williams",
    userRole: "Nurse",
    action: "Updated prescription",
    resource: "Prescription",
    resourceId: "PR-2034",
    details: "Modified dosage for medication 'Amoxicillin' from '500mg twice daily' to '750mg twice daily'.",
    status: "success",
    category: "user",
    ipAddress: "192.168.1.67"
  },
  {
    id: "log_123456791",
    timestamp: "2025-04-10T11:05:47",
    user: "Admin User",
    userRole: "Administrator",
    action: "Changed user permissions",
    resource: "User",
    resourceId: "U-0023",
    details: "Modified role permissions for user 'Nurse Johnson' from 'Staff Nurse' to 'Head Nurse'. Added permissions: manage_staff, approve_medications.",
    status: "success",
    category: "security",
    ipAddress: "192.168.1.12"
  },
  {
    id: "log_123456792",
    timestamp: "2025-04-10T12:18:33",
    user: "System",
    userRole: "System",
    action: "Backup completed",
    resource: "Database",
    resourceId: "",
    details: "Automated daily backup completed successfully. Backup size: 2.4GB. Files stored at backup/daily/2025-04-10/.",
    status: "success",
    category: "system",
    ipAddress: "127.0.0.1"
  },
  {
    id: "log_123456793",
    timestamp: "2025-04-10T13:45:22",
    user: "Emma Davis",
    userRole: "Receptionist",
    action: "Scheduled appointment",
    resource: "Appointment",
    resourceId: "A-3045",
    details: "Scheduled new appointment for patient Michael Brown (P-0982) with Dr. Sarah Johnson on 2025-04-15 at 10:30 AM for 'Follow-up consultation'.",
    status: "success",
    category: "user",
    ipAddress: "192.168.1.89"
  },
  {
    id: "log_123456794",
    timestamp: "2025-04-10T14:02:19",
    user: "Dr. Sarah Johnson",
    userRole: "Doctor",
    action: "Created lab request",
    resource: "Lab Request",
    resourceId: "LR-5672",
    details: "Created new lab request for patient Emily White (P-2345). Tests requested: Complete Blood Count, Lipid Profile, Liver Function Tests.",
    status: "success",
    category: "user",
    ipAddress: "192.168.1.53"
  },
  {
    id: "log_123456795",
    timestamp: "2025-04-10T15:30:05",
    user: "Finance Officer",
    userRole: "Finance",
    action: "Generated invoice",
    resource: "Invoice",
    resourceId: "INV-8976",
    details: "Generated invoice for patient Robert Johnson (P-3498) for services: Consultation ($75), Blood Test ($120), X-Ray ($250). Total amount: $445.",
    status: "success",
    category: "user",
    ipAddress: "192.168.1.78"
  },
  {
    id: "log_123456796",
    timestamp: "2025-04-10T16:20:14",
    user: "Unknown",
    userRole: "Unknown",
    action: "Failed login attempt",
    resource: "Authentication",
    resourceId: "",
    details: "Failed login attempt for username 'admin' from IP 203.0.113.45. Attempt 3 of 5 before account lockout.",
    status: "failure",
    category: "security",
    ipAddress: "203.0.113.45"
  },
  {
    id: "log_123456797",
    timestamp: "2025-04-10T17:05:38",
    user: "System",
    userRole: "System",
    action: "API rate limit exceeded",
    resource: "API",
    resourceId: "",
    details: "Rate limit exceeded for external patient data API. Request from client ID 'ext-service-23'. Limit: 100 requests per minute.",
    status: "warning",
    category: "system",
    ipAddress: "198.51.100.23"
  },
  {
    id: "log_123456798",
    timestamp: "2025-04-10T18:10:22",
    user: "Auto Scheduler",
    userRole: "System",
    action: "Automated reminder sent",
    resource: "Notification",
    resourceId: "N-6721",
    details: "Automated appointment reminder sent to 45 patients with appointments scheduled for tomorrow (2025-04-11).",
    status: "success",
    category: "system",
    ipAddress: "127.0.0.1"
  },
  {
    id: "log_123456799",
    timestamp: "2025-04-10T19:30:45",
    user: "Dr. Michael Chen",
    userRole: "Doctor",
    action: "Accessed patient history",
    resource: "Patient",
    resourceId: "P-4587",
    details: "Accessed complete medical history for patient David Wilson (P-4587) including sensitive data (mental health records).",
    status: "success",
    category: "security",
    ipAddress: "192.168.1.62"
  },
  {
    id: "log_123456800",
    timestamp: "2025-04-10T20:15:19",
    user: "Database Monitor",
    userRole: "System",
    action: "Database performance issue",
    resource: "Database",
    resourceId: "",
    details: "High database load detected. CPU usage at 92%, memory usage at 87%. Query response time increased to 3.2s average.",
    status: "warning",
    category: "system",
    ipAddress: "127.0.0.1"
  },
  {
    id: "log_123456801",
    timestamp: "2025-04-10T21:05:33",
    user: "Admin User",
    userRole: "Administrator",
    action: "System settings changed",
    resource: "Settings",
    resourceId: "",
    details: "Modified system settings:\n- Password policy updated (min length: 8 → 10 chars)\n- Session timeout changed (30 → 15 minutes)\n- Failed login attempts before lockout (5 → 3 attempts)",
    status: "success",
    category: "security",
    ipAddress: "192.168.1.12"
  },
  {
    id: "log_123456802",
    timestamp: "2025-04-10T22:45:11",
    user: "Pharmacy Interface",
    userRole: "System",
    action: "Integration error",
    resource: "External System",
    resourceId: "",
    details: "Failed to connect to external pharmacy system. Error: Connection timeout after 30s. Prescription PR-8765 could not be electronically transmitted.",
    status: "failure",
    category: "system",
    ipAddress: "10.0.5.23"
  },
  {
    id: "log_123456803",
    timestamp: "2025-04-10T23:30:04",
    user: "Security Monitor",
    userRole: "System",
    action: "Unusual access pattern",
    resource: "Data Access",
    resourceId: "",
    details: "Unusual access pattern detected for user 'James Wilson' (Staff Nurse). Accessed 47 different patient records in 15 minutes, significantly above typical usage pattern.",
    status: "warning",
    category: "security",
    ipAddress: "192.168.1.98"
  }
];
